echo "We are trying this practical from linux EC2"
echo "We are from batch-33 and learning git/gihub"
echo "We are learning Branching"
echo "I am learning Git"
echo "I am in github"
echo "I am in the branch2"
echo "I am in the branch b2"
echo "I am in branch1"
echo "I am doing my first change in github"
echo "Welcome to Github....!!!!!!"
echo "I am in the branch b1"
